name: tracker506

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-506tracker
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin1234
      MONGO_INITDB_DATABASE: 506trackerdb
    volumes:
      - mongo_506tracker_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

volumes:
  mongo_506tracker_data: