version: '3.9'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: ulacit_buses_api
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ..:/app
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - ulacit_net

  mongo:
    image: mongo:7.0
    container_name: ulacit_buses_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ulacit_net

  mongo-express:
    image: mongo-express:1.0.2
    container_name: ulacit_buses_mongo_ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongo
    networks:
      - ulacit_net

volumes:
  mongo_data:

networks:
  ulacit_net:
    driver: bridge
